### ISSUE TITLE
This still work with latest App Engine and Java?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dindinet/jsonengine#35]
```
Just curious if this works with the latest app engine + java?  It's probably 
something I am doing but just thought I would ask.

Getting the following error:

java.lang.AssertionError: java.lang.NoSuchMethodException: 
com.google.appengine.repackaged.com.google.common.base.intern
al.Finalizer.startFinalizer(java.lang.Class, java.lang.Object)


FULL TRACE

WARNING: Error for /_je/messages
java.lang.AssertionError: java.lang.NoSuchMethodException: 
com.google.appengine.repackaged.com.google.common.base.intern
al.Finalizer.startFinalizer(java.lang.Class, java.lang.Object)
        at com.google.appengine.repackaged.com.google.common.base.FinalizableReferenceQueue.getStartFinalizer(Finalizabl
eReferenceQueue.java:278)
        at com.google.appengine.repackaged.com.google.common.base.FinalizableReferenceQueue.<clinit>(FinalizableReferenc
eQueue.java:84)
        at com.google.appengine.repackaged.com.google.common.collect.Interners$WeakInterner.<clinit>(Interners.java:119)

        at com.google.appengine.repackaged.com.google.common.collect.Interners.newWeakInterner(Interners.java:61)
        at com.google.appengine.repackaged.com.google.io.protocol.ProtocolSupport.<clinit>(ProtocolSupport.java:55)
        at com.google.apphosting.api.DatastorePb$GetRequest.freeze(DatastorePb.java:8275)
        at com.google.apphosting.api.DatastorePb$GetRequest$1.<init>(DatastorePb.java:8201)
        at com.google.apphosting.api.DatastorePb$GetRequest.<clinit>(DatastorePb.java:8198)
        at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl.get(AsyncDatastoreServiceImpl.java:138)
        at com.google.appengine.api.datastore.DatastoreServiceImpl$1.runInternal(DatastoreServiceImpl.java:80)
        at com.google.appengine.api.datastore.DatastoreServiceImpl$1.runInternal(DatastoreServiceImpl.java:77)
        at com.google.appengine.api.datastore.TransactionRunner.runInTransaction(TransactionRunner.java:31)
        at com.google.appengine.api.datastore.DatastoreServiceImpl.get(DatastoreServiceImpl.java:77)
        at org.slim3.datastore.DatastoreUtil.getAsMap(DatastoreUtil.java:497)
        at org.slim3.datastore.Datastore.getAsMap(Datastore.java:1773)
        at org.slim3.datastore.Datastore.getAsMap(Datastore.java:1835)
        at org.slim3.datastore.Datastore.getAsMap(Datastore.java:1881)
        at org.slim3.datastore.Datastore.getOrNull(Datastore.java:819)
        at com.jsonengine.common.JEUserUtils.getDisplayName(JEUserUtils.java:88)
        at com.jsonengine.controller.FrontController.initJERequest(FrontController.java:254)
        at com.jsonengine.controller.FrontController.doQuery(FrontController.java:388)
        at com.jsonengine.controller.FrontController.run(FrontController.java:104)
        at org.slim3.controller.Controller.runBare(Controller.java:108)
        at org.slim3.controller.FrontController.processController(FrontController.java:567)
        at org.slim3.controller.FrontController.doFilter(FrontController.java:347)
        at org.slim3.controller.FrontController.doFilter(FrontController.java:300)
        at org.slim3.controller.FrontController.doFilter(FrontController.java:270)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.tools.development.BackendServersFilter.doFilter(BackendServersFilter.java:97)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:94)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
        at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
        at org.slim3.controller.HotRequestDispatcherWrapper.forward(HotRequestDispatcherWrapper.java:67)
        at org.slim3.controller.FrontController.doForward(FrontController.java:729)
        at org.slim3.controller.FrontController.doFilter(FrontController.java:306)
        at org.slim3.controller.FrontController.doFilter(FrontController.java:270)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.slim3.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:54)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.slim3.controller.HotReloadingFilter.doHotReloading(HotReloadingFilter.java:223)
        at org.slim3.controller.HotReloadingFilter.doFilter(HotReloadingFilter.java:187)
        at org.slim3.controller.HotReloadingFilter.doFilter(HotReloadingFilter.java:157)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:123)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:61)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at com.google.appengine.tools.development.BackendServersFilter.doFilter(BackendServersFilter.java:97)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:94)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.jav
a:383)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.NoSuchMethodException: 
com.google.appengine.repackaged.com.google.common.base.internal.Finalizer.st
artFinalizer(java.lang.Class, java.lang.Object)
        at java.lang.Class.getMethod(Unknown Source)
        at com.google.appengine.repackaged.com.google.common.base.FinalizableReferenceQueue.getStartFinalizer(Finalizabl
eReferenceQueue.java:276)
        ... 79 more

```

Original issue reported on code.google.com by `ralbe...@gmail.com` on 17 Dec 2012 at 4:28

**Comment by kshivam213** [comment]
Anyone have solution then please post
